### ISSUE TITLE
NetData incorrectly offline

### ISSUE THREAD

**Issue by zaydons** [Monitorr/Monitorr#121]
## Your environment:

- **Operating system**: CentOS 7

- **Webserver**:       Apache/2.4.6 (CentOS)

- **PHP Version**:      PHP 5.6.33

- **Monitorr Branch**:   master

## Describe your issue:

I just added [NetData](https://my-netdata.io) to my stack, and I added it to my Monitorr config file; however it is showing the service as Offline.. has anyone else run into this issue? Running a fresh install of NetData, and no issues monitoring anything else.. 
When I do a `curl -I -L ip:19999` I am getting a 400 error.. which is strange since I can hit it in my browser.. 

Any assistance would be greatly appreciated.. Thanks for the awesome dashboard!

**Comment by seanvree** [comment]
@zaydons  we MAY be dealing with an "incompatible" service as explained at the top of the wiki:
https://github.com/Monitorr/Monitorr/wiki/05-Troubleshooting

However, IF the Netdata is running on that port the fallback check should report an "unresponsive" which means that there IS something on the port, but can't access the WebUI, but strange that it's showing offline. 

A couple question:

1 - I assume you're on the latest version of Monitorr?  

2 - Can you use the file in /assets/php/checkmanual.php  
Explained on the wiki under "7. Manual Testing "
You would insert that SAME address into the checkmanual.php file, then browse to it, and you SHOULD get response codes for BOTH the primary check (Curl) and the backup check (fsockopen). 

LMK what you find. 

Thanks for reporting.

**Comment by zaydons** [comment]
I am using the Latest version yes: Version: v0.13.3m is what is reported on the bottom of my screen 

I was/am using the http:// url to the port, sorry forgot to mention that in the initial ticket.. 

Doing the manual check just changing this line: ` $url = "http://192.168.1.168:19999";` 

And the output of the manual check:  

> Ping URL ............. 192.168.1.168:19999 
CURL ................... FAIL 
CURL Response .. HTTP : 400 / 400 / CODE: 0 / 0 
PING ................... SUCCESS 
PING Response ... (0) 
URL status .......... OPEN 

> Monitorr

> status .... UNRESPONSIVE 

> PING response headers:

> HTTP/1.1 200 OK
Connection: close
Server: NetData Embedded HTTP Server v1.9.0-379-gc3fb560_rolling
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Type: text/html; charset=utf-8
Date: Wed, 07 Feb 2018 06:00:07 GMT
Cache-Control: public
Expires: Thu, 08 Feb 2018 17:12:08 GMT
Content-Length: 324614
    netdata dashboard

**Comment by seanvree** [comment]
@zaydons 

OKay, so Montorr SHOULD be reporting UNRESPONSIVE (yellow) then, but your'e saying it's OFFLINE in the main UI?  Can you ensure the file at /monitorr/assets/php/check.php is the SAME as on the repo?  It's possible you have an old version of that file somehow?

As far as CURL actually failing (http 400), there's one of two issues going on:
1 - you can't curl to netdata because netadata has some type of restriciton...did a quick google search (as I don't use netdata) and it appears it IS compatible with CURL: https://github.com/firehol/netdata/wiki/receiving-netdata-metrics-from-shell-scripts
So, can you try and run 
```
curl -s http://localhost:19999/api/v1/allmetrics
```
2 - some type of URL re-write is changing the URL .  As you see HTTP 400 means there is no webpage there.  

We need to find out why CURL is reporting HTTP 400 Monitorr will NEVER show online if your'e getting a HTTP 400 status code. Unfortunately, I don't have a way to test that on my end,  let me know what you get back with the above CURL command.

**Comment by zaydons** [comment]
I just did a check of the files, and it looks like they were different.. I pulled the check.php file from the repo and now on the dashboard it is displaying "Unresponsive" (however not in yellow.. see attached image) 

And when I did that curl I get a wall of different NetData stuff 

![image](https://user-images.githubusercontent.com/9087799/35932101-c6f0b8f4-0c04-11e8-880b-11e9200fbe83.png)

**Comment by seanvree** [comment]
Okay, that's what I thought - this means you have to put in a specific endpoint for the check link  Try putting "http://localhost:19999/api/v1/allmetrics" into the config.php file, what status do you get then?


refresh browser cache for the nonresponsive mis-coloring.

**Comment by seanvree** [comment]
@zaydons  also, I THINK you might have a bad local repo.  You SHOULD have " HD used " along with the other system stats...not sure if that's because of the browser cache issue....if NOT, copy your config file, then wipe out your local monitorr repo and do a fresh GIT CLONE....I'm thinking some of your files didn't get updated.   After you get a new local repo, you can copy your servcies over from the old config file, but DO NOT simply copy the actual config file, as some things have changed. 

However, this is separate from the actual problem of CURL returning HTTP 400.

**Comment by zaydons** [comment]
alright just added added the http://localhost:19999/api/v1/allmetrics into my config file and unfortunately it is still displaying Unresponsive.. 

And I was also thinking I have a bad repo.. just did a backup and clone and the HD used part is there
![image](https://user-images.githubusercontent.com/9087799/35932890-055de236-0c07-11e8-817f-17362cb3c257.png)

**Comment by seanvree** [comment]
@zaydons  use that address in the checkmanual.php file.

**Comment by zaydons** [comment]
> Input URL .......... http://localhost:19999/api/v1/allmetrics
CURL URL ........ http://localhost:19999/api/v1/allmetrics 
! Abnormal URL detected ! 
(Above message is only a warning, script will attempt to check input URL) 

> Ping URL ............. localhost:19999/api/v1/allmetrics 
CURL ................... FAIL 
CURL Response .. HTTP : 400 / 400 / CODE: 0 / 0 
PING ................... SUCCESS 
PING Response ... (0) 
URL status .......... OPEN 

> Monitorr status .... UNRESPONSIVE 

> PING response headers:

> HTTP/1.1 200 OK
Connection: close
Server: NetData Embedded HTTP Server v1.9.0-379-gc3fb560_rolling
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Type: text/html; charset=utf-8
Date: Wed, 07 Feb 2018 06:00:07 GMT
Cache-Control: public
Expires: Thu, 08 Feb 2018 18:04:14 GMT
Content-Length: 324614
    netdata dashboard

**Comment by seanvree** [comment]
Yeah, still HTTP 400...you gotta find out why netdata won't accept a CURL request. I don't have netdata to test with. It's possible you can't curl from PHP to netdata.

**Comment by zaydons** [comment]
hmm ok I'll see what I can do trying to track it down tonight... If I happen to find anything to get it working is there anywhere I can put the info for a future person who has the same issue?

**Comment by seanvree** [comment]
DEF! I'm interested, I'll throw it on the wiki if we can determine something is weird about netdata.

Appreciate you helping out. 

Def LMK

**Comment by seanvree** [comment]
@zaydons  so, just did some tests.  You're right, it's not you. It's netdata.  For some reason it won't accept PHP curl.  I assume it's a security feature.  

I'd suggest two things at this point - 

- open an issue with netdata and ask specifically about PHP curl. 
- YOu can edit the monitorr code to show ONLINE.  It will still show offline if it goes offline. See the wiki here under para 5.g. 

https://github.com/Monitorr/Monitorr/wiki/05-Troubleshooting

Def let me know if you find anything out.

**Comment by seanvree** [comment]
Added to wiki. Closing this issue. Feel free to comment if further progress is made
