### ISSUE TITLE
FEAT:  Add SystemInfo

### ISSUE THREAD

**Issue by seanvree** [Monitorr/Monitorr#20]
This is gonna be a big feature, but I think it's really needed. 

one tile that will list server/system resources, don't wanna get to crazy with this, just the basics here. a quick list right now:
- [x] CPU
- [x] MEM
- [x] UPtime
- [x] PING RT

**Comment by wjbeckett** [comment]
I like the look of these.
https://photos.app.goo.gl/wIZQxVM4RMwUhXah2

**Comment by seanvree** [comment]
@wjbeckett  yup! Something VERY simple like that will do!

**Comment by seanvree** [comment]
@wjbeckett  have you done any work on this?  

Can we go ahead and push SOMETHING?  I think it's a great feat.  LMK.

**Comment by wjbeckett** [comment]
Added some system info to the systeminfo branch in commit https://github.com/seanvree/Monitorr/commit/73643001c004cfda063b6e87c3976ebb8a48f491

Just CPU, Mem and uptime right now. 

I figure HDD info won't be very good because people will be running this on docker/vms/other systems potentially independent of their storage systems. So the data would be inaccurate and would only measure HDD data for where monitorr is running. 

I'll look at adding ping RT next.

**Comment by seanvree** [comment]
@wjbeckett   check this for Ping:

https://github.com/d4rk22/Network-Status-Page/blob/master/assets/php/ping_ajax.php

**Comment by wjbeckett** [comment]
Need to add color changes when CPU/ram is above thresholds.

**Comment by wjbeckett** [comment]
added dynamic badge colors in https://github.com/Monitorr/Monitorr/commit/64f08ad2b064b7c3100c3c5cb35910f78b22df5f
