### ISSUE TITLE
BUG: Unraid Ram Usage

### ISSUE THREAD

**Issue by jrdnlc** [Monitorr/Monitorr#39]
Running this using unraid under a nginx docker container and memory usage shows `98.49%`. I have a total of 128gb ram and I know for a fact that amount is not accurate.

**Comment by seanvree** [comment]
@jrdnlc  okay, we'll look into it.  How much is the usage off by?  Any estimate?  What webserver are you using?

THX

**Comment by wjbeckett** [comment]
It's a Nginx docker on unRaid. 
I'll run up a docker on my unRaid server and test it out.

**Comment by wjbeckett** [comment]
@jrdnlc unfortunately we won't be able to accurately display CPU and ram for docker instances. 

Purely because of the way Docker works. Your host (in this case unRaid), only exposes a very small amount of compute and storage resources to your container by design. It's how containers run so lean. 

So the figures you're seeing are correct. It's measuring the container, not the host. It'll only monitor the resources where the web app runs. And because containers don't expose any of the host system, we can't monitor those resources.

**Comment by jrdnlc** [comment]
Thanks for looking into it. The current status page I run now shows the actual cpu usage. I’ll see how it was implemented. 

Thinking about it though. I think it’s displaying how much ram is free and not actually what’s being used @wjbeckett

**Comment by seanvree** [comment]
@jrdnlc should be how much ram/CPU is used.

**Comment by seanvree** [comment]
possible fix for this:

https://github.com/Monitorr/Monitorr/issues/193
