### ISSUE TITLE
Off-centered

### ISSUE THREAD

**Issue by veganexe** [Monitorr/Monitorr#54]
![monitorr](https://user-images.githubusercontent.com/29048693/31382296-ca94e5e0-add4-11e7-857e-c426e8893ba9.png)
 
The container is off-centered

**Comment by veganexe** [comment]
Why "wontfix"? Can you please give me a workaround at least? Monitorr is just perfect for my project even at this stage. Just need to fix the centering. Using 128x128 cards

**Comment by seanvree** [comment]
@veganexe you've edited the css too much.  There's no way to tell why it's not centered.  But, if I had to guess, I would say it's something with the clock.

**Comment by wjbeckett** [comment]
The reason it's a wontfix is because you've change so much we wouldn't know where to begin to troubleshoot. 

Monitorr is built on Bootstrap so modifying the CSS can start to cause issues. 

Can you add some more tiles (so there is at least 6) and see if you still have the issue?

**Comment by veganexe** [comment]
Adding more tiles did not help, here are the diff logs

diffchecker.com/dsaG4xNz
diffchecker.com/FPWLdX0B

**Comment by jrdnlc** [comment]
Where did you get that theme? Did you create it yourself? @veganexe

**Comment by veganexe** [comment]
Yes, I did.

And back to the topic, it seems it is off centered by default. Try keeping 4 tiles and a single word header and view in the Mobile mode of your browser to see that off-centered container

**Comment by wjbeckett** [comment]
No issues here.
Again, this is because you have modified the CSS and index enough that it has broken the Bootstrap layout.


![Uploading Screenshot_20171011-105157.png…]()

**Comment by veganexe** [comment]
:3 it looked off for me. Anyway can you please take a look at the diff log and try to find the issue? I don't want that theming work to go useless cuz of a teeny off-center :(

**Comment by wjbeckett** [comment]
My screenshot clearly shows that the _DEFAULT_ unmodified theme is not off centre.
We will not troubleshoot your issue for you at this stage as theming is not on our roadmap just yet. 
Because of how Bootstrap works with Monitorr, adjusting the index and CSS will absolutely cause issues if you don't stick to Bootstrap methods.

I would suggest that you roll back your changes to the tile sizes and any index modifications and make sure it works for you 'out of the box'.

Then, change the div from col-lg-4 to col-lg-1. That might get you in the right direction.

Again, we will not be fixing this issue for you as theming is not on our roadmap just yet. This issue will remain closed and tagged as wontfix.

**Comment by jonfinley** [comment]
Just to add, It's not that we are no supporting theming or anything of the sort, by all means! While this project grows please by all means offer ideas, make changes, show us what we could incorporate, etc. As one of the main CSS contributors, I'd heavily consider what @wjbeckett recommend, starting from scratch to ensure that the project does indeed work as it is supposed to. After that, then start tweaking down. At this moment, We agree that we are not offering full support towards theming but in the future would definitively like to offer a way for all users to be able to tweak the CSS. :)
