### ISSUE TITLE
Ram percentage higher than 100%

### ISSUE THREAD

**Issue by 47094623** [Monitorr/Monitorr#67]
System stats:
PHP 5.6.12
Win 10 v. 1703 (OS Build 15063.674)
CPU: Ryzen 1700
32 GB Ram

![image](https://user-images.githubusercontent.com/30420691/31829275-643fade2-b582-11e7-823b-e80d7e44529b.png)

CPU seems correct, ping seems correct, uptime is stuck at 0, RAM is over 100%

**Comment by seanvree** [comment]
@47094623  what version of PHP are you running?

**Comment by rudyolph** [comment]
This issue with the RAM being over 100% is because the getRamTotal() and getRamFree() functions are returning the results as int and that has a max value of about 2 billion so calling TotalPhysicalMemory on windows which returns the value in bytes will well exceed 2 billion.  You need to return those values as a double or a float to have it work properly.

**Comment by seanvree** [comment]
@47094623  I have pushed a possible fix to the test branch here:

https://github.com/Monitorr/Monitorr/tree/test

Please test and report back if this fixes your issue.

**Comment by seanvree** [comment]
fix with:  https://github.com/Monitorr/Monitorr/releases/tag/v0.12.0m
